server:
  port: 9003

spring:
  application:
    name: cloud-zuul
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:9004

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    # 路由名称，随意
    multi-consumer:
      # 路由地址
      path: /multi/consumer/**
      # 该路由地址对应的服务名称
      serviceId: multi-consumer
    multi-provider:
      path: /multi/provider/**
      serviceId: multi-provider
    simple-consumer:
      path: /simple/consumer/**
      serviceId: simple-consumer
    simple-provider:
      path: /simple/provider/**
      serviceId: simple-provider
